### PR TITLE
feat: extend `parameters` to support `matrix`

### PR DESCRIPTION
**Pull request by mdovhopo**
Hey @albertodonato, first of all thank you for this exporter, it is awesome.

There is one feature, that i lack, so i implemented it myself and it would be nice if You consider including it in to the `main` branch :3

The problem:
I needed to get items prices in our tables for different marketplaces & for different price ranges. With current `parameters` property i could only specify price ranges, and copy query for each marketplace

The solution:
I come up with `parameters_matrix` (similar to github action's matrix) which will run query for each permutation of each matrix dimension.

Example with parameters:
```yaml
      query_amazon:
        databases: [db]
        metrics: [total_amount]
        sql: |
          select 
            count(1) AS total_amount, 
            "amazon" as marketplace, 
            concat(:price__low, '-', :price__high) aas range
          from items
          where 
            mp = "amazon" and 
            price > :price__low and 
            price <= :price__high;
        parameters:
          - low: 0
            high: 100
          - low: 100
            high: 200
      query_ebay:
        databases: [db]
        metrics: [total_amount]
        sql: |
          select 
            count(1) AS total_amount, 
            "amazon" as marketplace, 
            concat(:price__low, '-', :price__high) aas range
          from items
          where 
            mp = "ebay" and 
            price > :price__low and 
            price <= :price__high;
        parameters:
          - low: 0
            high: 100
          - low: 100
            high: 200
```

Example with `parameters_matrix`:
```yaml
      query:
        databases: [db]
        metrics: [total_amount]
        sql: |
          select 
            count(1) AS total_amount, 
            mp as marketplace, 
            concat(:price__low, '-', :price__high) aas range
          from items
          where 
            mp = :mp__name and 
            price > :price__low and 
            price <= :price__high;
        parameters_matrix:
            mp:
              - name: amazon
              - name: ebay
            price:
              - low: 0
                high: 100
              - low: 100
                high: 200
```

I have added:
- implementation
- new test cases
- docs

Any feedback would be much appreciated :)

P.S. I am no python dev, so sorry for bad code)

### CODE REVIEW

**Comment by albertodonato** [comment]
Hi @mdovhopo, thanks for proposing this!

The matrix format looks good, although I'm actually thinking that `parameters_matrix` could just be declared as `parameters`, so there's a single config key for parameters.
In the original case the value is a list of values, in the new form is a dict as you described, so there's no ambiguity in the meaning.

Makes sense?

**Comment by mdovhopo** [comment]
Are you saying that format in `parameters_matrix` should just replace `parameters` (1)?
Or we just merge `parameters_matrix` and `parameters` into `parameters` (2)?

I would prefer (2) option, just to not introduce breaking change to configuration.

**Comment by albertodonato** [comment]
Yes, I meant (2) as well, so it expands `paameters` functionality without breaking b/c.

**Comment by mdovhopo** [comment]
Okay, this make total sense. I will take a look later today, thanks for the feedback.

**Comment by mdovhopo** [comment]
@albertodonato FYI, PR is ready for 2nd review :3

**Comment by albertodonato** [comment]
@mdovhopo thanks!
Would you mind rebasing it on current main and squashing commits to a single one?

**Comment by mdovhopo** [comment]
@albertodonato done, all rebased & squashed into one commit

**Comment by albertodonato** [comment]
I've extracted the matrix creation logic and added a direct test (so that's easier to see what gets generated), and reworded the documentation a bit, but the logic hasn't changed.

Thanks again for the contribution!

**Pull request merged**
