### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Docjones**
Added libxml2 to Dockerfile, which is needed for ibm_db

### CODE REVIEW

**Comment by albertodonato** [comment]
thanks!

**Comment by Docjones** [comment]
Thanks for merging. Two questions:
1. is there a schedule for the next release?
2. i am trying to use db2 database (using `dsn: ibm_db_sa:// ...`) and still get an error upon start:

```
error from database "c03": module "ibm_db" not found
module "ibm_db" not found`
```
Any idea how to get the underlying problem?

**Comment by albertodonato** [comment]
The dns for db2 should be `db2+ibm_db://...`.
Can you try if that works for you?

I'll push the fix for the Dockerfile in the next release soon.

**Comment by Docjones** [comment]
> The dns for db2 should be `db2+ibm_db://...`.
> Can you try if that works for you?

That doesn't work either, i am sorry... i tried the following:
```
db2+ibm_db_sa://<user>:<pass>@<ip>:<port>/<database>;
ibm_db://<user>:<pass>@<ip>:<port>/<database>;
```
these two give an "Invalid database DSN"
```
ibm_db_sa://<user>:<pass>@<ip>:<port>/<database>;
db2+ibm_db://<user>:<pass>@<ip>:<port>/<database>;
```
these two give an "module "ibm_db" not found"

The rest of the testing configuration is pretty much forward:
```
databases:
  c03:
    dsn: <...>

metrics:
  metric1:
    type: gauge
    description: test

queries:
  query1:
    interval: 5
    databases: [c03]
    metrics: [metric1]
    sql: SELECT RAND() as metric1 FROM SYSIBM.SYSDUMMY1

```
> I'll push the fix for the Dockerfile in the next release soon.

Thanks :)

**Pull request merged**
